### ISSUE TITLE
#保研询问

### ISSUE THREAD

**Issue by GitAlice123** [NamelessOIer/Clique-Percolation#1]
学长你好，看了您的保研经验贴觉得有一些感兴趣的内容，今年保研想向您咨询一点事情

**Comment by NamelessOIer** [comment]
你好，很高兴我的经验帖能对你有所帮助！如果你有问题需要咨询，可以在经验帖的评论区咨询，如果不方便公开问也可以留下你的联系方式。另外，由于本 issue 与本仓库无关，我将在一周后删除该 issue。
